source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

target 'TUSafariActivity', :exclusive => true do
  pod "TUSafariActivity", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TUSafariActivity", :path => "../"
end
