source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.0'
inhibit_all_warnings!

target 'TUSafariActivity' do
  pod "TUSafariActivity", :path => "../"
end

target 'Tests' do
  pod "TUSafariActivity", :path => "../"
end
